# -*- coding: utf-8 -*-
"""Men's Tennis ATP Stats 2024 Web Scraping - W/L Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmJMTKzAM1RcXJt9h0etWehzG7n6SsLW
"""

# Web Scraping Imports
from bs4 import BeautifulSoup
import requests

# Set the URL for the webpage containing 2024 ATP Tour Tennis Stats
url = 'https://www.coretennis.net/majic/pageServer/19010000ll/en/2024-ATP-Tour-Tennis-Stats.html'

# Send an HTTP GET request to the URL to retrieve the page content
page = requests.get(url)

# Parse the retrieved page content with BeautifulSoup, specifying 'html' as the parser format
soup = BeautifulSoup(page.text, 'html')

# Find all <table> elements on the page and select the first one (index [0]), which contains the data we are looking for
table = soup.find_all('table')[0]

# Within the selected table, find all <tr> (table row) elements and select the first row, which is where the column headers are
stat_titles = table.find_all('tr')[0]

# Find all <td> elements in the first row (stat_titles) and extract their text content
stat_table_titles = [title.get_text(strip=True) for title in stat_titles.find_all('td')]

# Filter out any empty strings
stat_table_titles = [title for title in stat_table_titles if title]

# Eliminate "#" column (excluding first column)
stat_table_titles = stat_table_titles[1:]

# Import pandas for dataframe usage
import pandas as pd

# Create dataframe with previously stored column titles
df = pd.DataFrame(columns = stat_table_titles)

# Find all the rows in the table
column_data = table.find_all('tr')

# Create a list to hold the data, excluding the first column
data_without_first_column = []

# Flag to skip the first row (header row)
skip_first_row = True

# Loop through each row
for row in column_data:
    # Find all <td> elements in the row
    cells = row.find_all('td')

    # Skip the first row (header row) by checking the flag
    if skip_first_row:
        skip_first_row = False
        continue  # Skip this iteration

    # If the row contains data (ignores rows without <td> tags)
    if cells:
        # Exclude the first column (index 0), and add the rest of the columns
        row_data = [cell.text.strip() for cell in cells[1:]]

        # Append the processed row data to the dataframe
        df.loc[len(df)] = row_data

# Print resulting data
print(df)

# Export as a CSV file
df.to_csv('ATP2024MensTennisStats.csv', index=False)